### ISSUE TITLE
Continuous kotlin.jvm.KotlinReflectionNotSupportedError

### ISSUE THREAD

**Issue by ArnyminerZ** [DevSrSouza/KotlinBukkitAPI#9]
### Log message:
```
[15:56:42 ERROR]: Could not pass event PlayerMoveEvent to KotlinBukkitAPI v0.1.0-SNAPSHOT
kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath
        at kotlin.jvm.internal.ClassReference.error(ClassReference.kt:79) ~[?:?]
        at kotlin.jvm.internal.ClassReference.isInstance(ClassReference.kt:33) ~[?:?]
        at kotlin.reflect.full.KClasses.safeCast(KClasses.kt:269) ~[?:?]
        at br.com.devsrsouza.kotlinbukkitapi.controllers.PlayerController$onEnable$$inlined$event$2.execute(ExEvent.kt:27) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-155]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-155]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1115) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-155]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-155]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

### build.gradle
```
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.71'
    id 'kr.entree.spigradle' version '1.2.3'
}

group 'org.example'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/") }
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven {
        name = "KotlinBukkitAPI"
        url = "http://nexus.devsrsouza.com.br/repository/maven-public/"
    }
    jitpack() // For vault
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    testCompile group: 'junit', name: 'junit', version: '4.12'
    implementation "org.jetbrains.kotlin:kotlin-reflect"

    compileOnly spigot()
    compileOnly vault()
    compileOnly("br.com.devsrsouza.kotlinbukkitapi:core:0.1.0-SNAPSHOT") // core
}

spigot {
    ...
    apiVersion = '1.15'
    load = POST_WORLD
    depends = ['KotlinBukkitAPI'...]
    ...
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

### Events Snippet:
```
events {
     if (config.getBoolean("drops.player-head.enable", true))
        event<PlayerDeathEvent> {
            val player = this.entity
            this.drops.add(item(Material.PLAYER_HEAD).meta<SkullMeta> { owningPlayer = player })
        }
}
```

**Comment by DevSrSouza** [comment]
Tkx for reporting, and sorry that take so long to fix it.

Future plans is to remove for complete the usage of Kotlin Reflect on the project migrating configuration to Kotlinx.serialization.
